# Generated by Django 4.2.7 on 2024-05-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabAgence',
            fields=[
                ('id', models.CharField(db_column='Code_Agence', max_length=15, primary_key=True, serialize=False)),
                ('libelle', models.CharField(db_column='Libelle_Agence', max_length=50)),
                ('compte_comptable', models.CharField(blank=True, db_column='Compte_Comptable', max_length=10, null=True)),
                ('est_bloquer', models.BooleanField(blank=True, db_column='Est_Bloquer', null=True)),
                ('user_id', models.CharField(blank=True, db_column='User_ID', max_length=15, null=True)),
                ('date_modification', models.DateTimeField(blank=True, db_column='Date_Modification', null=True)),
            ],
            options={
                'db_table': 'Tab_agence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabBanque',
            fields=[
                ('code_banque', models.CharField(db_column='Code_Banque', max_length=15, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, db_column='Libelle_Banque', max_length=50, null=True)),
                ('acronyme', models.CharField(blank=True, db_column='Acronyme', max_length=20, null=True)),
                ('est_bloquer', models.BooleanField(blank=True, db_column='Est_Bloquer', null=True)),
                ('user_id', models.CharField(blank=True, db_column='User_ID', max_length=15, null=True)),
                ('date_modification', models.DateTimeField(blank=True, db_column='Date_Modification', null=True)),
            ],
            options={
                'db_table': 'tab_banque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabCommune',
            fields=[
                ('id', models.CharField(db_column='Code_Commune_Ons', max_length=10, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, db_column='Libelle_Commune', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Tab_Commune',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabDivision',
            fields=[
                ('id', models.CharField(db_column='Code_Division', max_length=15, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, db_column='Libelle_Division', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tab_Division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabFiliale',
            fields=[
                ('id', models.CharField(db_column='Code_Filiale', max_length=5, primary_key=True, serialize=False)),
                ('code_entreprise', models.CharField(db_column='Code_Entreprise', max_length=2)),
                ('libelle', models.CharField(blank=True, db_column='Libelle_Filiale', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Tab_filiale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabProduction',
            fields=[
                ('id_production', models.AutoField(db_column='ID_Production', primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type_production', models.CharField(db_column='Code_Type_Production', max_length=2, verbose_name='Type Production')),
                ('code_site', models.CharField(db_column='Code_site', max_length=500, verbose_name='Code Site')),
                ('code_filiale', models.CharField(blank=True, db_column='Code_Filiale', max_length=5, null=True, verbose_name='Code Filiale')),
                ('nt', models.CharField(blank=True, db_column='NT', max_length=20, null=True, verbose_name='NT')),
                ('code_groupeactivite', models.CharField(blank=True, db_column='Code_GroupeActivite', max_length=4, null=True, verbose_name="Code groupe d'activité")),
                ('code_activite', models.CharField(blank=True, db_column='Code_Activite', max_length=4, null=True, verbose_name='Code Activité')),
                ('code_tache', models.CharField(blank=True, db_column='Code_Tache', max_length=30, null=True, verbose_name='Code Tache')),
                ('recepteur', models.CharField(blank=True, db_column='Recepteur', max_length=20, null=True, verbose_name='Recepteur')),
                ('code_produit', models.CharField(blank=True, db_column='Code_Produit', max_length=4, null=True, verbose_name='Code Produit')),
                ('code_unite_mesure', models.CharField(blank=True, db_column='Code_Unite_Mesure', max_length=4, null=True, verbose_name='Unite')),
                ('type_prestation', models.SmallIntegerField(blank=True, db_column='Type_Prestation', null=True, verbose_name='Type Prestation')),
                ('mmaa', models.DateField(db_column='Mmaa')),
                ('quantite_1', models.FloatField(blank=True, db_column='Quantite_1', null=True, verbose_name='Quantite')),
                ('valeur_1', models.DecimalField(blank=True, db_column='Valeur_1', decimal_places=4, max_digits=19, null=True, verbose_name='Valeur')),
                ('quantite_2', models.FloatField(blank=True, db_column='Quantite_2', null=True, verbose_name='Quantite')),
                ('valeur_2', models.DecimalField(blank=True, db_column='Valeur_2', decimal_places=4, max_digits=19, null=True, verbose_name='Valeur')),
                ('quantite_3', models.FloatField(blank=True, db_column='Quantite_3', null=True, verbose_name='Quantite')),
                ('valeur_3', models.DecimalField(blank=True, db_column='Valeur_3', decimal_places=4, max_digits=19, null=True, verbose_name='Valeur')),
                ('prevu_realiser', models.CharField(db_column='Prevu_Realiser', max_length=1)),
                ('est_cloturer', models.BooleanField(blank=True, db_column='Est_Cloturer', null=True)),
                ('user_id', models.CharField(blank=True, db_column='User_ID', max_length=15, null=True)),
                ('date_modification', models.DateTimeField(blank=True, db_column='Date_Modification', null=True)),
            ],
            options={
                'db_table': 'Tab_Production',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabSituationNt',
            fields=[
                ('id', models.CharField(db_column='Code_Situation_NT', max_length=2, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, db_column='Libelle_Situation_NT', max_length=50, null=True)),
                ('est_bloquer', models.BooleanField(blank=True, db_column='Est_Bloquer', null=True)),
                ('user_id', models.CharField(blank=True, db_column='User_ID', max_length=15, null=True)),
                ('date_modification', models.DateTimeField(blank=True, db_column='Date_Modification', null=True)),
            ],
            options={
                'db_table': 'Tab_Situation_NT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabUniteDeMesure',
            fields=[
                ('id', models.CharField(db_column='Code_Unite_Mesure', max_length=4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, db_column='Symbole_Unite', max_length=10, null=True)),
                ('libelle_unite', models.CharField(blank=True, db_column='Libelle_Unite', max_length=50, null=True)),
                ('est_bloquer', models.BooleanField(blank=True, db_column='Est_Bloquer', null=True)),
                ('user_id', models.CharField(blank=True, db_column='User_ID', max_length=15, null=True)),
                ('date_modification', models.DateTimeField(blank=True, db_column='Date_Modification', null=True)),
            ],
            options={
                'db_table': 'Tab_Unite_de_mesure',
                'managed': False,
            },
        ),
    ]
