# Generated by Django 4.2.7 on 2024-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nt',
            name='date_cloture_nt',
            field=models.DateField(db_column='Date_Cloture_NT', null=True, verbose_name='Cloture'),
        ),
    ]
