# Generated by Django 4.2.13 on 2024-06-24 14:03

import api_sm.models
from django.db import migrations, models
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncaissementsRg',
            fields=[
                ('id', models.BigAutoField(db_column='Id_Enc_RG', primary_key=True, serialize=False)),
                ('date_encaissement', models.DateField(db_column='Date_Encaissement', verbose_name="Date d' Encaissement")),
                ('montant_encaisse', models.FloatField(db_column='Montant_Encaisse', verbose_name='Montant')),
                ('numero_piece', models.CharField(db_column='Numero_Piece', max_length=30, verbose_name='N° de piéce')),
                ('code_agence', models.CharField(blank=True, db_column='Code_Agence', max_length=15, null=True, verbose_name='Agence')),
                ('code_site', models.CharField(db_column='Code_Site', max_length=10)),
                ('nt', models.CharField(db_column='NT', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, db_column='Mode_Paiement', max_length=3, null=True, verbose_name='Mode Paiement')),
                ('est_bloquer', models.BooleanField(db_column='Est_Bloquer', default=False, editable=False)),
                ('user_id', models.CharField(db_column='User_ID', default=django_currentuser.middleware.get_current_user, editable=False, max_length=15)),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='Date_Modification')),
            ],
            options={
                'db_table': 'Encaissements_RG',
                'managed': False,
            },
            bases=(api_sm.models.DeleteMixin, models.Model),
        ),
    ]
