# Generated by Django 4.2.7 on 2024-05-09 15:42

from django.db import migrations, models
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='user_id',
            field=models.CharField(db_column='User_ID', default=django_currentuser.middleware.get_current_user, editable=False, max_length=15),
        ),
    ]
