# Generated by Django 4.2.7 on 2024-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_marche_est_bloquer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqe',
            name='libelle',
            field=models.TextField(db_column='Libelle_Tache', verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='historicaldqe',
            name='libelle',
            field=models.TextField(db_column='Libelle_Tache', verbose_name='Libellé'),
        ),
    ]
