# Generated by Django 4.2.7 on 2024-05-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_marche_est_bloquer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dqe',
            options={'managed': False, 'permissions': [('upload_dqe', 'Can upload DQE'), ('download_dqe', 'Can download DQE')], 'verbose_name': 'DQE', 'verbose_name_plural': 'DQE'},
        ),
    ]
