# Generated by Django 4.2.7 on 2024-04-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_alter_nt_date_cloture_nt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmarche',
            name='libelle',
            field=models.TextField(verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='libelle',
            field=models.TextField(verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='nt',
            name='libelle',
            field=models.TextField(blank=True, db_column='Libelle_NT', null=True, verbose_name='Libelle'),
        ),
    ]
