# Generated by Django 4.2.7 on 2024-04-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_alter_historicalmarche_libelle_alter_marche_libelle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='montant_ava_remb',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='montant_avf_remb',
        ),
    ]
