# Generated by Django 4.2.7 on 2024-04-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0006_remove_factures_montant_factureht_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='is_remb',
        ),
    ]
