# Generated by Django 4.2.7 on 2024-04-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sch', '0001_initial'),
        ('api_sm', '0008_alter_nt_options_alter_historicalmarche_nt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqe',
            name='unite',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api_sch.tabunitedemesure', verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='historicaldqe',
            name='unite',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_sch.tabunitedemesure', verbose_name='Unité'),
        ),
    ]
